services:
  - type: web
    name: flask-gpt-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api:app"
    envVars:
      - key: OPENAI_API_KEY
        value: "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"
      - key: SENDGRID_API_KEY
        value: "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"
      - key: SENDGRID_FROM_EMAIL
        value: michael@justresults.co
